// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvhttgkfviczreqhrozl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aHR0Z2tmdmljenJlcWhyb3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTYyNTIsImV4cCI6MjA3NDU3MjI1Mn0.WyIzKa6mES5RmMYmB5t3giI4HaSjrJmbybFK22uR6H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});